# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d845ee8899617644ea25c95fdd715a43345ffdbb24a5c719ef69ed81de6c3c1fda1fd3e4e25fb0899d244600d093a7a3c1c2e800a208c27d2d6087443383b3d

test:
  secret_key_base: 0a91581a86f31f0edf68fb3174b4c16c74e6aeaee43c4cb6aad55536f318117cd0952c0ce13d0c0e028d2c4ffebb94c49ce2a3483a49d5bcd86dd16f26cbf315

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
